version: "3.2"

services:
    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        depends_on:
            - backend

    backend:
        build: ./backend
        volumes:
            - ./backend:/app
        ports:
            - 8000:8000
