name: Backend CI

on:
    push:
        branches: [main]
        paths:
            - "backend/**"
            - ".github/workflows/**"
    pull_request:
        branches:
            - main
            - develop
        paths:
            - "backend/**"
            - ".github/workflows/**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/requirements.txt

            - name: Run tests with coverage
              run: |
                  cd backend
                  python -m coverage run -m pytest tests
                  coverage report
