name: Backend CI

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.8" # Adjust as necessary

            - name: Create and activate virtual environment
              run: |
                  python -m venv .venv
                  echo "source .venv/bin/activate" >> $GITHUB_ENV

            - name: Install dependencies
              run: |
                  pip install -r backend/requirements.txt

            - name: Run tests with coverage
              run: |
                  cd backend
                  python3 -m coverage run -m pytest tests
                  coverage report
